# Generated by Django 6.0.6 on 2026-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
