# Generated by Django 6.0.6 on 2026-08-14 14:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mensagem_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
    ]
