# Generated by Django 6.0.6 on 2026-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='James', max_length=100),
            preserve_default=False,
        ),
    ]
