# Generated by Django 6.0.6 on 2026-08-27 14:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=300)),
                ('sobre', models.TextField()),
                ('contatos', tinymce.models.HTMLField()),
            ],
        ),
    ]
